name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
      - name: Visual regression
        run: npx loki --requireReference --reactUri file:./storybook-static
