name: Percy
on:
  push:
    branches:
      - main

env:
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook --quiet
      - name: Visual regression
        run: npx percy storybook ./storybook-static
